server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location = /lava-verify_751e93edad61d6f3.html {
        default_type text/html;
    }
}
